# Generated by Django 5.2.5 on 2025-08-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_set_fixed_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unprocessed', 'Необработанный'), ('processing', 'В обработке'), ('in_delivery', 'В доставке'), ('completed', 'Выполнен'), ('cancelled', 'Отменен')], default='unprocessed', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
