# Generated by Django 5.2.5 on 2025-08-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unprocessed', 'Необработанный'), ('processing', 'В обработке'), ('in_delivery', 'В доставке'), ('completed', 'Выполнен'), ('cancelled', 'Отменен')], db_index=True, default='unprocessed', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
