# Generated by Django 5.2.5 on 2025-08-21 10:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_remove_order_products_orderproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Продукт в заказе', 'verbose_name_plural': 'Продукты в заказе'},
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='fixed_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Фиксированная цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default='-', max_length=250, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
