# Generated by Django 5.2.5 on 2025-08-21 10:48

from django.db import migrations
from django.db.models import F


def set_fixed_prices(apps, schema_editor):
    OrderProduct = apps.get_model('foodcartapp', 'OrderProduct')
    Product = apps.get_model('foodcartapp', 'Product')
    for order_product in OrderProduct.objects.all():
        product = Product.objects.get(id=order_product.product_id)
        order_product.fixed_price = product.price
        order_product.save()

class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_alter_order_options_alter_orderproduct_options_and_more'),
    ]

    operations = [
        migrations.RunPython(set_fixed_prices, reverse_code=migrations.RunPython.noop),
    ]
