# Generated by Django 5.2.5 on 2025-08-23 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_order_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='comments',
            new_name='comment',
        ),
    ]
