# Generated by Django 5.2.5 on 2025-08-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_rename_comments_order_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, default='-', null=True, verbose_name='Комментарий'),
        ),
    ]
