# Generated by Django 5.2.5 on 2025-09-01 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_alter_order_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='registrated_at',
            new_name='registered_at',
        ),
    ]
