# Generated by Django 5.2.5 on 2025-09-01 15:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_rename_registrated_at_order_registered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='fixed_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Фиксированная цена'),
        ),
    ]
