# Generated by Django 5.2.5 on 2025-09-01 15:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_alter_orderproduct_fixed_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='fixed_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Фиксированная цена'),
        ),
    ]
